apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: ${NS_SERVICES}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: registry.redhat.io/rhel9/redis-7:latest
          ports:
            - containerPort: 6379
          env:
            - name: REDIS_PASSWORD
              value: "${REDIS_PASSWORD}"
          readinessProbe:
            tcpSocket:
              port: 6379
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
---
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: ${NS_SERVICES}
spec:
  selector:
    app: redis
  ports:
    - port: 6379
      targetPort: 6379
