apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: ${BERT_MODEL_NAME}
  namespace: ${NS_MODELS}
  annotations:
    serving.kserve.io/deploymentMode: RawDeployment
  labels:
    opendatahub.io/dashboard: "true"
spec:
  predictor:
    model:
      modelFormat:
        name: custom
      runtime: bert-intent-runtime
