# ServingRuntime: bge-small-en-v1.5 (CPU — vLLM CPU)
# Source: intent-classification-sidd namespace
apiVersion: serving.kserve.io/v1alpha1
kind: ServingRuntime
metadata:
  annotations:
    opendatahub.io/apiProtocol: REST
    opendatahub.io/runtime-version: v0.9.1.0
    opendatahub.io/template-display-name: CvLLM CPU (amd) ServingRuntime for KServe
    opendatahub.io/template-name: template-5d71ra
    openshift.io/display-name: CvLLM CPU (amd) ServingRuntime for KServe
  labels:
    opendatahub.io/dashboard: "true"
  name: bge-small-en-v15
  namespace: ${NS_MODELS}
spec:
  annotations:
    opendatahub.io/kserve-runtime: vllm
    prometheus.io/path: /metrics
    prometheus.io/port: "8080"
  containers:
  - args:
    - --port=8080
    - --model=/mnt/models
    - --served-model-name={{.Name}}
    command:
    - python
    - -m
    - vllm.entrypoints.openai.api_server
    env:
    - name: HF_HOME
      value: /tmp/hf_home
    image: registry.redhat.io/rhaii-early-access/vllm-cpu-rhel9:3.4.0-ea.2-1774640877
    name: kserve-container
    ports:
    - containerPort: 8080
      protocol: TCP
  multiModel: false
  supportedModelFormats:
  - autoSelect: true
    name: vLLM
